services:
  - type: web
    name: budget-gm-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PORT
        value: 10000
      - key: SECRET_KEY
        generateValue: true
    healthCheckPath: /api/player_pool
    autoDeploy: true

  - type: web
    name: budget-gm-frontend
    env: node
    buildCommand: cd budget-gm-frontend && npm install && npm run build
    startCommand: cd budget-gm-frontend && npm start
    envVars:
      - key: REACT_APP_API_URL
        sync: false
        value: https://budget-gm-backend.onrender.com
      - key: PORT
        value: 3000
    healthCheckPath: /
    autoDeploy: true 